### PR TITLE
new file:   Inbetriebnahme-Echolink-Hat.txt Beschreibung Inebtriebnahme

### PR DESCRIPTION
**Pull request by hb9gvd**
Ich hab einen Text erstellt, wie man das Printli in Betrieb nimmt. Bildli mit Pinout von Raspi folgt.

### CODE REVIEW

**Comment by hb9gvd** [comment]
Added test chapter to README.md and a Pi Header image

**Comment by mweyland** [comment]
Very nice work! I noticed that we need to run
```
echo out > direction
```
after exporting the pin (before the two echo statements). Could you perhaps add these?

**Comment by mweyland** [comment]
Found another minor issue (sorry). I think the correct steps for audio testing are:
1. Start `alsamixer`, hit F6 and activate sound card 1 (`snd_rpi_proto`). Activate the `Output Mixer HiFi` item and set `CAPTURE` for the `Line` item. 
2. Run `arecord -V stereo -fdat -D 'hw:CARD=sndrpiproto,DEV=0' > /dev/null` and observe the VU meter while injecting a signal into the left and the right channel. Once this works, `arecord` can be used to record a sample (e.g. `test.wav`) for playback in the next step.
3. Play back the sample using `aplay -D 'plughw:CARD=sndrpiproto,DEV=0' test.wav`

**Comment by hb9gvd** [comment]
Thank you for testing my testing and commenting. I changed README.md according to your inputs.

**Pull request merged**
